name: envCraFT
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - jupyter-book
  - matplotlib
  - numpy
  - xarray
  - pip
  - pip:
    - -e git+https://github.com/ThomasChauve/xarrayuvecs.git@main#egg=xarrayuvecs
    - -e git+https://github.com/ThomasChauve/xarrayaita.git@main#egg=xarrayaita
    - -e git+https://github.com/ThomasChauve/xarray_symTensor2d.git@main#egg=xarray_symTensor2d
    - -e git+https://github.com/ThomasChauve/xarray_craft.git@main#egg=xarray_craft
